# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # See https://github.com/i11/packer
  config.vm.box = "ubuntu-puppet-base"

  config.vm.provision "shell", :inline => <<-SHELL
    apt-get update
  SHELL

  config.vm.provision "puppet" do |puppet|
     puppet.module_path = "../../"
     puppet.manifest_file = "vagrant.pp"
  end
end
